expo install  @react-native-community/masked-view
expo install  @react-navigation/bottom-tabs
expo install  @react-navigation/drawer
expo install  @react-navigation/material-top-tabs
expo install  @react-navigation/native
expo install  @react-navigation/stack
expo install  expo
expo install  expo-font
expo install  expo-linear-gradient
expo install  expo-status-bar
expo install  moment
expo install  prop-types
expo install  react
expo install  react-dom
expo install  react-native-app-intro-slider
expo install  react-native-calendars
expo install  react-native-confirmation-code-field
expo install  react-native-gesture-handler
expo install  react-native-gifted-chat
expo install  react-native-iphone-x-helper
expo install  react-native-keyboard-aware-scroll-view
expo install  react-native-linear-gradient
expo install  react-native-maps
expo install  react-native-maps-directions
expo install  react-native-modalize
expo install  react-native-reanimated
expo install  react-native-safe-area-context
expo install  react-native-scaling-drawer
expo install  react-native-screens
expo install  react-native-simple-dialogs
expo install  react-native-size-matters
expo install  react-native-snap-carousel
expo install  react-native-svg
expo install  react-native-web
expo install  react-navigation
expo install  react-navigation-tabs
expo install  react-test-renderer
